import fs from 'node:fs';import crypto from 'node:crypto';
import {normalizeTiming} from '../../../engine/import.mjs';
const project=new URL('../',import.meta.url),file=new URL('sources/words.json',project),d=JSON.parse(fs.readFileSync(file,'utf8'));
const lyrics=fs.readFileSync(new URL('sources/canonical-lyrics.txt',project),'utf8').split(/\r?\n/).map(s=>s.trim()).filter(s=>s&&!s.startsWith('['));
const normalized=normalizeTiming(d,{duration:219.96});const issues=[];if(lyrics.join(' ')!==d.words.map(w=>w.text).join(' '))issues.push('Canonical words differ');
if(lyrics.length!==d.phrases.length)issues.push('Phrase count differs');for(let i=0;i<lyrics.length;i++)if(lyrics[i]!==d.phrases[i].text)issues.push(`Phrase ${i} differs`);
if(new Set(d.words.map(w=>w.id)).size!==d.words.length)issues.push('Duplicate word IDs');
for(let i=0;i<d.words.length;i++){const w=d.words[i];if(!Number.isFinite(w.start)||!Number.isFinite(w.end)||w.start<0||w.end<=w.start||w.end>d.duration)issues.push(`Invalid interval ${w.id}`);if(i&&w.start<d.words[i-1].end-1e-6)issues.push(`Overlapping words ${w.id}`);const raw=JSON.parse(fs.readFileSync(w.provenance.artifact,'utf8'));if(!raw.words.some(x=>x.text===w.text&&x.start===w.start&&x.end===w.end))issues.push(`Cue not intact measured interval ${w.id}`);}
const hash=x=>crypto.createHash('sha256').update(fs.readFileSync(x)).digest('hex');if(hash(d.source.audio)!==d.source.sha256)issues.push('Audio hash differs');
const result={version:1,status:issues.length?'failed':'schema_and_provenance_passed',audioSha256:d.source.sha256,timingSha256:hash(file),canonicalExact:lyrics.join(' ')===d.words.map(w=>w.text).join(' '),words:normalized.words.length,phrases:normalized.phrases.length,firstVocalStart:d.words[0].start,lastVocalEnd:d.words.at(-1).end,issues,sourceSupportedWords:d.summary.sourceSupported,unsupportedWords:d.summary.unsupported,encodedAudioGate:'pending',listened:false,note:'Valid canonical content, durable IDs and actual acoustic intervals. This report does not certify all sung-word boundaries or encoded audio.'};fs.writeFileSync(new URL('timing-validation.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(issues.length)process.exitCode=1;
