/** Full-film QA adapter for the authored HyperFrames composition. Never mutates lyric timing. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {loadProject,validateProject,fileHash,atomicJson,resolveSource} from '../../engine/project.mjs';
import {computeRevision,checkReview,VISUAL_RUBRIC} from '../../engine/gauntlet.mjs';
import {reviewAudio,decodeAudio,compareWaveforms} from '../../engine/audio-review.mjs';
import {reviewLyricVisibility} from '../../engine/ocr.mjs';
import {reviewTemporalActivity,validateTemporalReport} from '../../engine/temporal-review.mjs';
const projectDir=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(projectDir,'../..'),work=path.join(root,'output/psalm91-production'),projectPath=path.join(projectDir,'project.json');
const args=process.argv.slice(2),arg=(flag,fallback)=>args.includes(flag)?args[args.indexOf(flag)+1]:fallback,videoPath=path.resolve(arg('--video',path.join(work,'psalm91-shelter-v1.mp4'))),outDir=path.resolve(arg('--out',path.join(work,'review-full'))),run=promisify(execFile),read=async p=>JSON.parse(await fs.readFile(p,'utf8'));
const exists=async p=>{try{return (await fs.stat(p)).isFile()}catch{return false}},progress=(stage,detail={})=>console.log(JSON.stringify({stage,...detail}));
const command=(tool,args,timeout=600000)=>run(tool,args,{timeout,maxBuffer:32*1024*1024});

async function prepare(){
 const timing=await read(path.join(projectDir,'sources/words.json')),plan=await read(path.join(projectDir,'scene-plan.json')),attacks=await read(path.join(projectDir,'sources/measured-audio-events.json'));
 const assets={},mediaAssets={};
 const fontFamilies={'BebasNeue-Regular.ttf':'Bebas','ArchivoBlack-Regular.ttf':'Archivo','EBGaramond-Italic-Variable.ttf':'Elegy'};
 for(const filename of (await fs.readdir(path.join(projectDir,'assets'))).sort()){
  const id=path.basename(filename,path.extname(filename)).replace(/[^A-Za-z0-9_.-]/g,'-'),src=`assets/${filename}`;
  if(/\.(png|jpe?g|webp)$/i.test(filename))assets[id]={type:'image',src};
  else if(/\.(ttf|otf|woff2?)$/i.test(filename))assets[id]={type:'font',src,family:fontFamilies[filename]??id};
  else if(/\.(mp4|mov|webm)$/i.test(filename))mediaAssets[id]={type:'video',src};
 }
 const productionInputs={reviewRunner:{src:'review.mjs'},compiled:{src:'index.html'},template:{src:'composition.html.txt'},opening:{src:'opening.js'},narrative:{src:'narrative.js'},builder:{src:'build.mjs'},timeline:{src:'sources/words.json'},scenePlan:{src:'scene-plan.json'},gsap:{src:'vendor/gsap.min.js'},measuredEnergy:{src:'sources/measured-energy.json'}};
 if(await exists(path.join(projectDir,'asset-map.json')))productionInputs.assetMap={src:'asset-map.json'};
 const phrases=timing.phrases,sections=[];
 const descriptors=[{id:'p91-opening',start:0,words:timing.words.filter(w=>w.phraseId==='p91-l001'),phraseId:'p91-l001',family:'opening-shelter-world'},...phrases.filter(p=>p.id!=='p91-l001').map(p=>({id:p.id,start:p.start,words:timing.words.filter(w=>w.phraseId===p.id),phraseId:p.id,family:plan.scenes.find(s=>s.id===p.id)?.family??'authored-lyric-scene'})),{id:'p91-outro-instrumental-review',start:Math.max(phrases.at(-1).end+.35,295),words:[],family:'shelter-return-and-horizon'}].sort((a,b)=>a.start-b.start);
 for(let i=0;i<descriptors.length;i++){const d=descriptors[i],scene=plan.scenes.find(s=>s.id===d.phraseId);sections.push({id:d.id,start:d.start,end:descriptors[i+1]?.start??327.6,style:'verse',seed:91000+i,wordIds:d.words.map(w=>w.id),assetIds:[],direction:{...(scene?.direction??{}),backend:'hyperframes',reviewRegion:true,choreography:d.family,note:'Review coverage region. The verse style is an engine-schema compatibility label; pictures are authored in bound HyperFrames HTML, not the Canvas verse renderer.'}})}
 const project={version:1,id:'psalm91-shelter',title:'Psalm 91 (LXX 90) — A Thousand Shall Fall',width:1920,height:1080,fps:30,duration:327.6,audio:{src:'assets/song.m4a',offset:0},source:{title:'Psalm 91 (LXX 90) A Thousand Shall Fall',start:0,end:327.6,audioDuration:327.6,audioSha256:timing.source.sha256},palette:{ink:'#090909',paper:'#f4ead6',accent:'#c77746'},assets,mediaAssets,productionInputs,words:timing.words,phrases,beats:attacks.beats,sections,intake:{status:'timed_needs_review',timingVerified:false,originalAudio:'assets/song.m4a',originalLyrics:'sources/performance-lyrics.txt',originalTiming:'sources/words.json',originalBeats:'sources/measured-audio-events.json',suppliedLyrics:'sources/canonical-lyrics.txt',warnings:['All literal supplied words preserved; one independently recognized performed repetition adds7words.','Strict source support86/396 is preparation only. Final encoded audio and OCR review remain required.']},quality:{maxStaticSeconds:4},renderBackend:{name:'hyperframes',version:'0.8.79',compositionId:'p91-shelter',entry:{src:'index.html'},adapterPurpose:'Engine-compatible review manifest; render through pinned HyperFrames CLI.'},creation:{stylePrompt:'Approved Word Journey plus Photo Reveal, copper/charcoal/ivory Shelter palette, sparse keyholes, lyric-first spatial choreography, sparse locally rendered supporting motion.'},hyperframesReviewPolicy:{minDistinctLyricChoreographies:30,maxUsesPerChoreography:3,canonicalWordCount:396,sourceSupportNotAcceptance:true,independentEncodedReviewRequired:true,canvasCreativePolicyApplicable:false,note:'Authored HyperFrames families are assessed from bound scene-plan.json and decoded film, not relabeled as Canvas catalog treatments.'}};
 const check=await validateProject(project,projectPath);if(!check.valid)throw Error(check.errors.join('\n'));await atomicJson(projectPath,project);progress('manifest-prepared',{projectPath,words:project.words.length,phrases:phrases.length,sections:sections.length,assets:Object.keys(assets).length,mediaAssets:Object.keys(mediaAssets).length});return project;
}
async function compiledMatches(project){
 const html=await fs.readFile(path.join(projectDir,'index.html'),'utf8'),match=html.match(/<script>window\.P91_DATA=([\s\S]*?);<\/script>/);if(!match)throw Error('Compiled P91_DATA missing');const data=JSON.parse(match[1]);
 const simplify=ws=>ws.map(w=>[w.id,w.text,w.start,w.end,w.phraseId]);if(data.duration!==project.duration||JSON.stringify(simplify(data.words))!==JSON.stringify(simplify(project.words)))throw Error('Compiled duration or canonical words differ from review manifest; build full327.6s HTML and prepare manifest before render');
 if(data.phrases.length!==56)throw Error('Compiled phrase coverage does not include all56performed phrases');return data;
}
if(args.includes('--prepare')){await prepare();process.exit(0)}
const {project}=await loadProject(projectPath);await compiledMatches(project);await fs.mkdir(outDir,{recursive:true});
const renderStartPath=`${videoPath}.render-start.json`,renderMetadataPath=`${videoPath}.render.json`;
if(args.includes('--capture-render-start')){const record={schemaVersion:1,kind:'hyperframes-render-start',projectPath,videoPath,capturedAt:new Date().toISOString(),sourceRevision:await computeRevision(projectPath),expected:{duration:project.duration,fps:project.fps,width:project.width,height:project.height,frames:Math.round(project.duration*project.fps)}};await atomicJson(renderStartPath,record);progress('render-start-captured',{renderStartPath});process.exit(0)}
if(args.includes('--capture-render-end')){const start=await read(renderStartPath),end=await computeRevision(projectPath);if(start.projectPath!==projectPath||start.videoPath!==videoPath||start.sourceRevision.revisionHash!==end.revisionHash)throw Error('Render input hashes changed; refusing render provenance');const metadata={schemaVersion:1,kind:'hyperframes-render-provenance',sha256:await fileHash(videoPath),sourceRevision:start.sourceRevision,sourceRevisionEnd:end,duration:project.duration,fps:project.fps,width:project.width,height:project.height,renderStartedAt:start.capturedAt,renderEndedAt:new Date().toISOString(),renderer:'HyperFrames0.8.79',note:'Source snapshot captured before rendering and verified after; output encoding is separately decoded by review.'};await atomicJson(renderMetadataPath,metadata);progress('render-end-captured',{renderMetadataPath});process.exit(0)}
const revision=await computeRevision(projectPath),videoSha256=await fileHash(videoPath),binding={videoSha256,projectHash:revision.projectHash,rendererHash:revision.rendererHash,revisionHash:revision.revisionHash};
const technical=[],check=(name,passed,observed,expected=null)=>technical.push({name,passed:!!passed,observed,expected});
const started=new Date().toISOString();progress('review-start',{videoPath,words:project.words.length});
const {stdout}=await command('ffprobe',['-v','error','-count_frames','-show_streams','-show_format','-of','json',videoPath]);const probe=JSON.parse(stdout),v=probe.streams.find(s=>s.codec_type==='video'),a=probe.streams.filter(s=>s.codec_type==='audio');
check('encodedFormat',v?.codec_name==='h264'&&v?.width===1920&&v?.height===1080&&v?.avg_frame_rate==='30/1'&&Number(v?.nb_read_frames)===9828&&a.length===1&&a[0].codec_name==='aac',{video:v?.codec_name,width:v?.width,height:v?.height,fps:v?.avg_frame_rate,frames:v?.nb_read_frames,audioTracks:a.length,audioCodec:a[0]?.codec_name},{videoCodec:'h264',width:1920,height:1080,fps:'30/1',frames:9828,audioTracks:1,audioCodec:'aac'});
try{await command('ffmpeg',['-v','error','-xerror','-i',videoPath,'-map','0:v:0','-map','0:a:0','-f','null','-']);check('safeDecode',true,'All video/audio packets decoded')}catch(e){check('safeDecode',false,e.stderr??e.message)}
const sourceAudio=resolveSource(projectPath,project.audio.src),wave=compareWaveforms(await decodeAudio(sourceAudio,{sourceOffset:0,duration:327.6}),await decodeAudio(videoPath));await atomicJson(path.join(outDir,'waveform.json'),{binding,sourceAudioSha256:await fileHash(sourceAudio),...wave});
check('decodedAudioMatch',wave.correlation>=.985&&wave.minSegmentCorrelation>=.97&&Math.abs(wave.gainDb??Infinity)<=.75,{correlation:wave.correlation,minSegmentCorrelation:wave.minSegmentCorrelation,gainDb:wave.gainDb},{minCorrelation:.985,minSegmentCorrelation:.97,maxAbsoluteGainDb:.75});check('audioLag',Math.abs(wave.offsetSeconds)<=.035,{offsetSeconds:wave.offsetSeconds},{maxAbsoluteSeconds:.035});check('audioDuration',Math.abs(wave.encodedDuration-327.6)<=.08&&Math.abs(wave.sourceDuration-327.6)<=.08,{source:wave.sourceDuration,encoded:wave.encodedDuration},{expected:327.6,tolerance:.08});
let metadata=null;try{metadata=await read(renderMetadataPath);check('renderOutputBinding',metadata.sha256===videoSha256,metadata.sha256,videoSha256);check('renderRevisionBinding',metadata.sourceRevision?.revisionHash===revision.revisionHash&&metadata.sourceRevisionEnd?.revisionHash===revision.revisionHash,{start:metadata.sourceRevision?.revisionHash,end:metadata.sourceRevisionEnd?.revisionHash},revision.revisionHash)}catch(e){check('renderProvenanceAvailable',false,e.message,'Pre-render and post-render source snapshots required; no retroactive proof')}
const plan=await read(path.join(projectDir,'scene-plan.json')),counts={};for(const s of plan.scenes)counts[s.family]=(counts[s.family]??0)+1;const missing=project.phrases.filter(p=>p.id!=='p91-l001'&&!plan.scenes.some(s=>s.id===p.id));const mechanical={uniqueFamilies:Object.keys(counts).length,maxUses:Math.max(...Object.values(counts)),missingPhraseIds:missing.map(p=>p.id),passed:Object.keys(counts).length>=30&&Math.max(...Object.values(counts))<=3&&!missing.length,note:'Distinct authored family IDs and coverage are structural checks; independent encoded visual review must judge meaningful variety.'};await atomicJson(path.join(outDir,'choreography-audit.json'),{binding,...mechanical});check('authoredChoreographyCoverage',mechanical.passed,mechanical,{minDistinctFamilies:30,maxUses:3,allPerformedPhrases:true});
const jobs=await Promise.allSettled([
 (async()=>{progress('strict-audio-start',{maxAttempts:1});const report=await reviewAudio({projectPath,videoPath,outDir:path.join(outDir,'audio'),repair:false,maxAttempts:1,threads:4,passTimeoutMs:180000});progress('strict-audio-complete',{status:report.status,verified:report.wordEvidence.filter(w=>w.passed).length,unsupported:report.wordEvidence.filter(w=>!w.supported).length});return report})(),
 (async()=>{progress('ocr-start',{requiredWords:project.words.length});const report=await reviewLyricVisibility({projectPath,videoPath,outDir:path.join(outDir,'ocr')});progress('ocr-complete',{status:report.status,coverage:report.coverage});return report})()
]);
const audio=jobs[0].status==='fulfilled'?jobs[0].value:{status:'failed',error:jobs[0].reason?.message},ocr=jobs[1].status==='fulfilled'?jobs[1].value:{status:'failed',error:jobs[1].reason?.message};if(jobs[0].status==='rejected')await atomicJson(path.join(outDir,'audio-execution-failure.json'),{binding,...audio});if(jobs[1].status==='rejected')await atomicJson(path.join(outDir,'ocr-execution-failure.json'),{binding,...ocr});
check('allCanonicalWordsSampled',ocr.coverage?.required===396,ocr.coverage??ocr.error,{required:396});check('encodedLyricVisibility',ocr.status==='passed',ocr.coverage??ocr.error,{requiredRatio:1});
progress('temporal-start');let temporal;try{const r=await reviewTemporalActivity({videoPath,project,outDir:path.join(outDir,'temporal')});temporal={path:r.reportPath,sha256:await fileHash(r.reportPath),present:true,...await validateTemporalReport(r,{videoSha256,project}),report:r}}catch(e){temporal={required:true,present:false,passed:false,errors:[e.message]}}check('temporalActivity',temporal.passed,{errors:temporal.errors,intervals:temporal.report?.intervals},{maxStaticSeconds:4});
const ending=await computeRevision(projectPath);check('unchangedDuringReview',ending.revisionHash===revision.revisionHash&&await fileHash(videoPath)===videoSha256,ending.revisionHash,revision.revisionHash);
const reportPath=path.join(outDir,'review.json'),report={schemaVersion:2,kind:'hyperframes-full-film-review-adapter',createdAt:started,reportPath,videoPath,projectPath,binding,revision,technical:{passed:technical.every(c=>c.passed),checks:technical,probe},evidence:{samples:(ocr.evidence??[]).map(f=>({time:f.time,path:f.path,sha256:f.sha256,reasons:['encoded-word-visibility']})),contactSheets:[],transitionStrips:[],note:'Reuses actual encoded OCR frames rather than decoding duplicate gauntlet samples.'},temporalActivity:temporal,renderProvenance:metadata?{path:renderMetadataPath,sha256:await fileHash(renderMetadataPath),verified:technical.filter(c=>c.name.startsWith('render')).every(c=>c.passed)}:{verified:false},visual:{status:'pending',threshold:8,rubric:VISUAL_RUBRIC,reviews:[],note:'Independent visual judgment is required; no score is synthesized by this script.'},machineAudio:audio.reportPath?{path:audio.reportPath,sha256:await fileHash(audio.reportPath),status:audio.status}:audio,lyricVisibility:{status:ocr.status,coverage:ocr.coverage,reportPath:ocr.reportPath},choreography:mechanical,sourceTimingPreparation:{sourceSupportCount:project.words.filter(w=>w.provenance.sourceAcousticSupported).length,wordCount:396,status:'not_encoded_acceptance'},limitations:['Strict audio failures remain failures; source estimates, OCR and good PCM correlation cannot approve unsupported lyric synchronization.','HyperFrames scene families are assessed by the authored manifest and independent encoded review, not the Canvas catalog.','An exact source binding and successful encode do not establish artistic quality.'],status:'pending-gauntlet-check'};
await atomicJson(reportPath,report);const state=await checkReview({reportPath,videoPath,projectPath,audioReviewPath:audio.reportPath});await atomicJson(path.join(outDir,'gate.json'),{passed:state.passed,status:state.status,reasons:state.reasons,quality:state.quality,binding});report.status=state.status;report.quality=state.quality;report.completedAt=new Date().toISOString();await atomicJson(reportPath,report);progress('review-complete',{reportPath,status:state.status,strictAudioStatus:audio.status,ocrCoverage:ocr.coverage,technicalPassed:report.technical.passed,independentVisualReview:'pending'});process.exitCode=state.passed?0:2;
