import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createCanvas,GlobalFonts} from '@napi-rs/canvas';
import {SCULPTURAL_CATALOG,sculpturalLayout,sculpturalPoses,drawSculpturalBackground,drawSculpturalTypography} from '../engine/sculptural-choreography.mjs';
for(const [file,family]of [['BebasNeue-Regular.ttf','Bebas Neue'],['ArchivoBlack-Regular.ttf','Archivo Black']])GlobalFonts.registerFromPath(new URL(`../assets/fonts/${file}`,import.meta.url).pathname,family);
const h={setFont(c,size,family){c.font=`${size}px "${family}"`;c.textAlign='center';c.textBaseline='alphabetic'},word(c,w,t,x,y,size,o={}){if(t<w.start)return;c.save();c.globalAlpha*=o.opacity??1;c.translate(x,y);c.rotate(o.rotate||0);c.scale(o.scale||1,o.scale||1);h.setFont(c,size,o.family);c.fillStyle=o.color||'#fff';c.fillText(w.text.toUpperCase(),0,0);c.restore()}};
const ids=Object.keys(SCULPTURAL_CATALOG);
function env(id,t=3,phrase='The blood of your brother cries from the ground'){const words=phrase.split(' ').filter(Boolean).map((text,i)=>({id:`w${i}`,text,start:.25+i*.31,end:.50+i*.31}));return{p:{words},s:{id:'test',start:0,end:6,wordIds:words.map(w=>w.id),direction:{choreography:id,heroIds:words.length?['w'+Math.floor(words.length/2)]:[]}},t,ink:'#060607',paper:'#f4f1ee',accent:'#e34656',seed:22,beat:0,assets:{}}}
const layout=()=>({positions:[],box:{x:180,y:185,w:1560,h:750}});
function raster(id,t=3,layer='all'){const canvas=createCanvas(480,270),c=canvas.getContext('2d');c.scale(.25,.25);const e=env(id,t);if(layer!=='type')drawSculpturalBackground(c,e,h);if(layer!=='background')drawSculpturalTypography(c,e,h,layout);return Buffer.from(c.getImageData(0,0,480,270).data)}
test('ten sculptural treatments preserve canonical cues and all words',()=>{assert.equal(ids.length,10);const c=createCanvas(1920,1080).getContext('2d');for(const id of ids)for(const phrase of ['', 'Cain', 'I killed him', 'The blood of your brother cries from the ground', 'From the beginning of the world there were many generations who lived upon the earth']){const e=env(id,3,phrase),before=JSON.stringify(e),m=sculpturalLayout(c,e,h,layout);assert.deepEqual(m.positions.map(o=>o.w.id).sort(),e.s.wordIds.toSorted(),id);for(const o of m.positions)assert.equal(o.w,e.p.words.find(w=>w.id===o.w.id));drawSculpturalBackground(c,e,h);drawSculpturalTypography(c,e,h,layout);assert.equal(JSON.stringify(e),before,id)}});
test('onset frames have full, immediate reading poses and no future word calls',()=>{const c=createCanvas(1920,1080).getContext('2d');for(const id of ids){const e=env(id),target=e.p.words[4];e.t=target.start;const calls=[];drawSculpturalTypography(c,e,{...h,word:(ctx,w,t,x,y,size,o)=>calls.push({w,t,x,y,size,o})},layout);assert.ok(calls.some(call=>call.w===target),id);assert.ok(calls.every(call=>call.w.start<=call.t&&call.t===e.t),id);assert.ok(calls.every(call=>call.o.opacity===1&&call.o.immediate===true&&call.o.motion==='none'),id);const pose=sculpturalPoses(c,e,h,layout).positions.find(o=>o.w===target);assert.equal(pose.visible,true);assert.ok(pose.scale>=.99)}});
test('protected text boxes keep active word geometry visible with no full-opacity overlap',()=>{const c=createCanvas(1920,1080).getContext('2d');for(const id of ids)for(const time of [.25,1.35,2.95,5.3]){const e=env(id,time);e.s.direction.textBox={x:240,y:160,w:1420,h:620};const m=sculpturalPoses(c,e,h,layout),b=m.box;for(const o of m.positions){assert.ok([o.x,o.y,o.size,o.scale,o.rotate,o.opacity].every(Number.isFinite),id);h.setFont(c,o.size,o.family);const width=c.measureText(o.w.text.replace(/[.,]$/,'').toUpperCase()).width*o.scale;assert.ok(o.x-width/2>=b.x-1&&o.x+width/2<=b.x+b.w+1,id);assert.ok(o.y-o.size*.86*o.scale>=b.y&&o.y<=b.y+b.h,id)}const boxes=m.positions.filter(o=>o.visible).map(o=>{h.setFont(c,o.size,o.family);return{left:o.x-c.measureText(o.w.text.toUpperCase()).width*o.scale/2,right:o.x+c.measureText(o.w.text.toUpperCase()).width*o.scale/2,top:o.y-o.size*.68*o.scale,bottom:o.y,id:o.w.id}});for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],z=boxes[j],overlapX=Math.min(a.right,z.right)-Math.max(a.left,z.left),overlapY=Math.min(a.bottom,z.bottom)-Math.max(a.top,z.top);assert.ok(overlapX<=2||overlapY<=2,`${id}: ${a.id} intersects ${z.id} by ${overlapX},${overlapY}`)}}});
test('sculptural silhouettes fill substantial areas and are visibly distinct',()=>{const hashes=new Set();for(const id of ids){const pixels=raster(id,3,'background'),occupied=Array.from(pixels).filter((v,i)=>i%4===3&&v>20).length;assert.ok(occupied>480*270*.07,`${id}: must be a solid mass, not hairlines (${occupied})`);hashes.add(createHash('sha256').update(pixels).digest('hex'))}assert.equal(hashes.size,10)});
test('each scene is repeatable under out-of-order frame seeking',()=>{for(const id of ids){const a=raster(id,3);raster(id,.1);raster(id,5.9);assert.deepEqual(raster(id,3),a,id);assert.notDeepEqual(raster(id,1.4),a,id)}});
test('photographic overlays remain translucent and do not clear source pixels',()=>{for(const id of ids){const canvas=createCanvas(480,270),c=canvas.getContext('2d');c.scale(.25,.25);const e=env(id);e.s.direction.photo='photo';drawSculpturalBackground(c,e,h);const data=c.getImageData(0,0,480,270).data;let opaque=0;for(let i=3;i<data.length;i+=4)if(data[i]>220)opaque++;assert.equal(opaque,0,id)}});
test('monument tearing waits until every word finishes its reading hold',()=>{const c=createCanvas(1920,1080).getContext('2d'),e=env('torn-monument'),end=Math.max(...e.p.words.map(w=>w.end));e.t=end+.20;assert.equal(sculpturalPoses(c,e,h,layout).tail,0);e.t=5.8;assert.ok(sculpturalPoses(c,e,h,layout).tail>.9)});
test('unknown choreography is left for the existing dispatcher',()=>{const c=createCanvas(10,10).getContext('2d'),e=env('unknown');assert.equal(sculpturalLayout(c,e,h,layout),null);assert.equal(drawSculpturalBackground(c,e,h),false);assert.equal(drawSculpturalTypography(c,e,h,layout),false)});
