import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {alignLexicalWords} from '../../../engine/audio-review.mjs';import {normalizeTiming} from '../../../engine/import.mjs';
const root=path.resolve('projects/genesis1-beginning'),out=path.join(root,'analysis'),dest=path.join(root,'timing'),read=p=>JSON.parse(fs.readFileSync(p)),source=read(path.join(dest,'performance-provisional.json')),windows=[...read(path.join(out,'opening-ctc-windows.json')),...read(path.join(out,'full-ctc-windows.json'))];
const ctc=fs.readdirSync(out).filter(f=>/^g1-l\d+(?:-r\d+)?-(?:opening|full|retry)-ctc-(base|large)\.json$/.test(f)).map(f=>read(path.join(out,f))).filter(p=>p.words?.length);
const asr=['opening-whisper-small.json','opening-whisper-medium.json','full-whisper-small.json','full-whisper-medium-diagnostic.json'].map(f=>path.join(out,f)).filter(fs.existsSync).map(read).filter(p=>p.words?.length);
const forced=['g1-l096-whisper-forced-small.json','g1-l096-whisper-forced-medium-diagnostic.json'].map(f=>read(path.join(out,f))).filter(p=>p.words?.length);
const words=[],reports=[],issues=[],globalColumns=[],globalExpected=[],phraseMeta=[];const retries=read(path.join(out,'retry-ctc-windows.json'));
for(const p of source.phrases){const expected=p.wordIds.map(id=>source.words.find(w=>w.id===id)),bound=retries.find(w=>w.id===p.id)??windows.find(w=>w.id===p.id);if(!bound)throw Error('No window '+p.id);
 const maps=asr.map(pass=>({...pass,matches:alignLexicalWords(expected,pass.words.filter(w=>w.end>bound.start&&w.start<bound.end)).matches}));
 const columns=expected.map((c,i)=>{let candidates=ctc.flatMap(pass=>{const word=pass.words.find(w=>w.canonicalId===c.id);return word?[{kind:'ctc',word,pass}]:[]});candidates.push(...forced.flatMap(pass=>{const word=pass.words.find(w=>w.canonicalId===c.id);return word?[{kind:'whisper_forced',word,pass}]:[]}));candidates.push(...maps.flatMap(pass=>pass.matches[i]?[{kind:'asr',word:pass.matches[i],pass}]:[]));candidates=candidates.filter(a=>Number.isFinite(a.word.start)&&a.word.end>a.word.start&&a.word.end<=304.721&&a.word.start>=bound.start-.05&&a.word.end<=bound.end+.15);
  const unique=new Map();for(const a of candidates)unique.set([a.pass.checkpointId,a.word.start,a.word.end].join(':'),a);candidates=[...unique.values()];
  for(const a of candidates){const q=a.word.provenance.tokenProbability??0;a.paired=candidates.filter(b=>b.kind==='ctc'&&a.kind==='ctc'&&a.pass.checkpointId!==b.pass.checkpointId&&Math.abs(a.word.start-b.word.start)<=.08&&Math.abs(a.word.end-b.word.end)<=.12);a.asrPeers=candidates.filter(b=>b.kind==='asr'&&b.pass.checkpointId!==a.pass.checkpointId&&(b.word.provenance.tokenProbability??0)>=.6&&Math.abs(a.word.start-b.word.start)<=.25&&Math.abs(a.word.end-b.word.end)<=.25);a.support=a.kind==='ctc'&&a.paired.length>0&&((q>=.7&&a.paired.some(b=>b.word.provenance.tokenProbability>=.7))||(q>=.2&&a.asrPeers.length>0));
   a.score=2*q+(a.paired.length?Math.min(q,...a.paired.map(b=>b.word.provenance.tokenProbability))>=.2?1.4:.2:0)+Math.min(2,new Set(a.asrPeers.map(peer=>peer.pass.checkpointId)).size)*.65+(a.kind==='ctc'&&String(a.pass.source.model).includes('large')?.15:0)+(a.kind==='asr'&&String(a.pass.source.model).includes('medium')?.1:0);
   if(a.kind==='whisper_forced'&&candidates.some(b=>b.kind==='whisper_forced'&&b.pass.checkpointId!==a.pass.checkpointId&&Math.abs(b.word.start-a.word.start)<=.06))a.score+=2.5;
   if(q<.2)a.score-=.8;if(a.kind==='whisper_forced'&&q<.2&&a.word.end-a.word.start<.08&&a.word.text.replace(/[^a-z]/gi,'').length>3)a.score-=.5;if(a.word.end-a.word.start>1.5&&!a.asrPeers.length)a.score-=1;
   // Whisper word starts often include instrumental gaps. Penalize only where two
   // independent CTC checkpoints locate the same later consonant and compatible end.
   if((i===0||a.word.start<31)&&a.kind==='asr'&&candidates.some(b=>b.kind==='ctc'&&b.word.provenance.tokenProbability>=.2&&b.word.start-a.word.start>(a.word.start<31?.15:.25)&&Math.abs(b.word.end-a.word.end)<.5&&candidates.some(d=>d.kind==='ctc'&&d.pass.checkpointId!==b.pass.checkpointId&&Math.abs(d.word.start-b.word.start)<=.08)))a.score-=2;
  }
  if(!candidates.length)throw Error('No actual measured candidates for '+c.id);return candidates;
 });
 globalColumns.push(...columns);globalExpected.push(...expected);phraseMeta.push({id:p.id,text:p.text,bound,words:[]});
}
let states=globalColumns[0].map(a=>({score:a.score,path:[a]}));for(let i=1;i<globalColumns.length;i++){const next=[];for(const a of globalColumns[i]){const previous=states.filter(s=>a.word.start>s.path.at(-1).word.start);if(previous.length){const penalized=previous.map(s=>({...s,adjusted:s.score-Math.max(0,s.path.at(-1).word.end-a.word.start-.12)*3}));const best=penalized.reduce((a,b)=>a.adjusted>b.adjusted?a:b);next.push({score:best.adjusted+a.score,path:[...best.path,a]});}}if(!next.length)throw Error('No globally ordered measured path at '+globalExpected[i].id);states=next;}
const chosen=states.reduce((a,b)=>a.score>b.score?a:b).path;
for(let i=0;i<chosen.length;i++){const a=chosen[i],c=globalExpected[i];words.push({...c,start:a.word.start,end:a.word.end,confidence:'machine_estimate',provenance:{method:a.kind==='ctc'?'local-torchaudio-ctc; canonical forced alignment':a.kind==='whisper_forced'?'local-openai-whisper; canonical forced alignment diagnostic':'local-openai-whisper; canonical exact token match',model:a.pass.source.model?path.basename(a.pass.source.model):'medium.en.pt',checkpointId:a.pass.checkpointId,tokenProbability:a.word.provenance.tokenProbability,timingVerified:false,sourceAcousticSupported:a.support,sourcePairedCheckpoints:a.paired.length>0,independentRecognitionSupport:a.asrPeers.length>0,forcedAlignment:a.kind==='whisper_forced',artifact:a.pass.artifact,encodedReview:'pending',note:'One unchanged measured acoustic interval selected. No interpolation or beat quantization.'}});phraseMeta.find(p=>p.id===c.phraseId).words.push({id:c.id,text:c.text,start:a.word.start,end:a.word.end,kind:a.kind,sourceSupported:a.support,artifact:a.pass.artifact,alternatives:globalColumns[i].map(x=>({kind:x.kind,start:x.word.start,end:x.word.end,probability:x.word.provenance.tokenProbability,selectionScore:x.score,artifact:x.pass.artifact}))});}
reports.push(...phraseMeta);
const phrases=source.phrases.map(p=>{const ws=words.filter(w=>w.phraseId===p.id);return {...p,start:ws[0].start,end:ws.at(-1).end,provenance:{method:'First and last selected actual acoustic word interval',timingVerified:false,performedSequenceEvidence:['analysis/provider-embedded-lyrics.txt','analysis/full-whisper-small.json','analysis/full-whisper-medium-diagnostic.json'],performanceRepeatOf:p.performedRepeat?p.sourcePhraseId:null}};});
for(let i=0;i<words.length-1;i++){if(words[i+1].start<=words[i].start)issues.push({kind:'nonmonotonic',before:words[i].id,after:words[i+1].id});if(words[i].end>words[i+1].start+.025)issues.push({kind:'acoustic-overlap',before:words[i].id,after:words[i+1].id,seconds:words[i].end-words[i+1].start});}
const gaps=[];let cursor=0;for(const p of phrases){if(p.start-cursor>=.8)gaps.push({start:cursor,end:p.start,duration:p.start-cursor,kind:'no-canonical-lyric-gap',provenance:{method:'Complement of measured phrase intervals; not a silence or vocal-presence classifier'}});cursor=Math.max(cursor,p.end);}if(304.72-cursor>=.8)gaps.push({start:cursor,end:304.72,duration:304.72-cursor,kind:'no-canonical-lyric-tail',provenance:{method:'After final measured canonical line; backing vocals and music may continue'}});
const manifest={version:1,timebase:'source',status:'machine_estimate',source:{...source.source,sha256:source.source.audioSha256,canonicalLyrics:'canonical-lyrics.txt',performanceLyrics:'performance-lyrics.txt',measuredAttacks:'../intake/measured-attacks.json',measuredEnergy:'../intake/energy-profile.json'},words,phrases,instrumentalIntervals:gaps,omittedSuppliedPhraseIds:source.omittedSuppliedPhraseIds,warnings:['Source-only acoustic preparation. Encoded AAC/OCR and visual review remain pending.','Exact supplied lyrics are archived separately. Performed sequence contains an audible repeated block and omits supplied lines g1-l078 through g1-l095.','Local speech-trained models give machine estimates; confidence is not calibrated singing timestamp accuracy. Raw failures remain in analysis/.','No-canonical-lyric gaps do not assert silence or lack of adlibs.']};
fs.writeFileSync(path.join(out,'selection-candidate.json'),JSON.stringify({manifest,reports,issues},null,2)+'\n');
const normalized=normalizeTiming(manifest,{duration:304.72,timebase:'source'});const summary={words:words.length,phrases:phrases.length,sourceSupported:words.filter(w=>w.provenance.sourceAcousticSupported).length,asrSelected:words.filter(w=>w.provenance.method.startsWith('local-openai')).length,issues,normalizedWords:normalized.words.length};
fs.writeFileSync(path.join(dest,'words.json'),JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(path.join(dest,'performance-lyrics.txt'),phrases.map(p=>p.text).join('\n')+'\n');fs.writeFileSync(path.join(dest,'phrase-outline.json'),JSON.stringify({version:1,timebase:'source',source:manifest.source,phrases,instrumentalIntervals:gaps},null,2)+'\n');fs.writeFileSync(path.join(out,'selection.json'),JSON.stringify({version:1,status:'source_only_machine_estimate',selectionMethod:'Supported ordered path over actual acoustic intervals. No imposed first-word anchor and no arbitrary overlap clipping.',summary,phrases:reports},null,2)+'\n');console.log(JSON.stringify(summary,null,2));
