"""Deliver the root-authorized, visually reviewed 32-second Genesis1 opening preview."""
from pathlib import Path
import datetime,hashlib,json,urllib.request,subprocess
from h3_jobs import remote,copy
ROOT=Path(__file__).resolve().parent; HOST='https://omipc.taild60b4e.ts.net'; src=Path('/Volumes/DATA/ArkRender/genesis1/genesis1-opening32.mp4'); pcm=Path('/Volumes/DATA/ArkRender/genesis1/opening32-audio.json'); qa=json.loads(pcm.read_text()); assert qa['offsetSeconds']==0 and qa['minSegmentCorrelation']>.99
raw=src.read_bytes();sha=hashlib.sha256(raw).hexdigest();md5=hashlib.md5(raw).hexdigest();prefix='C:/Users/sjfis/Videos/Genesis1/opening32-'+sha[:12];rp=prefix.replace('/','\\');thumb=ROOT/'opening32-thumbnail.jpg'
subprocess.run(['ffmpeg','-v','error','-ss','15','-i',str(src),'-frames:v','1','-y',str(thumb)],check=True)
metadata={'project':'Genesis1 - The Beginning','title':'Genesis 1 - Opening 32 seconds (lyric film preview)','version':'Opening 32s preview v1','sourceAgent':'Codex','sourceMachine':'Mac mini','sourcePath':str(src),'notes':f"32-second opening direction preview, not the complete song video. Completes the first seven phrases; 960 native rendered frames at1080p30. Composition agent independently accepted the decoded opening visuals; root authorized delivery. Source-versus-encoded audio PCM correlation0.999381, minimum2-second segment0.9977 and zero measured global lag, gain-0.0466dB. These audio transport checks do not certify every sung word timing. No perfect-sync or complete-gauntlet claim. Pending Shane review. SHA256 {sha}.",'status':'pending_review','path':rp+'.mp4','thumbnail':rp+'.jpg','expectedMd5':md5}
meta=ROOT/'opening32-app-metadata.json';meta.write_text(json.dumps(metadata,indent=2)+'\n');copy(src,prefix+'.mp4');copy(thumb,prefix+'.jpg');copy(meta,prefix+'.json');rsha=remote(f"(Get-FileHash -Algorithm SHA256 '{rp}.mp4').Hash").lower();assert rsha==sha
result=json.loads(remote(f"$body=Get-Content -Raw '{rp}.json';Invoke-RestMethod -Method Post -Uri http://127.0.0.1:4317/api/admin/videos/ingest -ContentType 'application/json' -Body $body|ConvertTo-Json -Depth 20"));(ROOT/'opening32-app-ingest.json').write_text(json.dumps(result,indent=2)+'\n');vid=result['video']['id'];watch=HOST+'/api/admin/videos/'+vid+'/media';download=watch+'?download=1'
with urllib.request.urlopen(download,timeout=60) as res: data=res.read();headers={'httpStatus':res.status,'contentType':res.headers.get('Content-Type'),'contentDisposition':res.headers.get('Content-Disposition')}
dsha=hashlib.sha256(data).hexdigest();assert dsha==sha
req=urllib.request.Request(watch,headers={'Range':'bytes=0-1023'})
with urllib.request.urlopen(req,timeout=30) as res: status=res.status;crange=res.headers.get('Content-Range');chunk=res.read()
assert status==206 and len(chunk)==1024
record={'id':'opening32','title':metadata['title'],'candidateId':vid,'status':result['video']['status'],'reviewUrl':HOST+'/studio#videos','watchUrl':watch,'downloadUrl':download,'localFile':str(src),'localSha256':sha,'remoteCopiedSha256':rsha,'remoteDownloadSha256':dsha,'bytes':len(data),'rangeStatus':status,'contentRange':crange,'duplicate':result.get('duplicate'),'audioEvidence':str(pcm),'audioEvidenceSha256':hashlib.sha256(pcm.read_bytes()).hexdigest(),'visualReview':'Root reported composition agent independent decoded acceptance; this publisher did not rescore the footage.','verifiedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),**headers}
(ROOT/'opening32-app-delivery.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(record,indent=2))
